
INSERT INTO Countries (Id, Name, Code, Language) VALUES (1,N'Andorra',N'AD',N'ca');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (2,N'United Arab Emirates',N'AE',N'ar');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (3,N'Afghanistan',N'AF',N'fa');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (4,N'Antigua and Barbuda',N'AG',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (5,N'Anguilla',N'AI',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (6,N'Albania',N'AL',N'sq');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (7,N'Armenia',N'AM',N'hy');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (8,N'Netherlands Antilles',N'AN',N'nl');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (9,N'Angola',N'AO',N'pt');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (10,N'Argentina',N'AR',N'es');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (11,N'Austria',N'AT',N'de');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (12,N'Australia',N'AU',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (13,N'Aruba',N'AW',N'nl');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (14,N'Azerbaijan',N'AZ',N'az');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (15,N'Bosnia and Herzegovina',N'BA',N'bs');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (16,N'Barbados',N'BB',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (17,N'Bangladesh',N'BD',N'bn');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (18,N'Belgium',N'BE',N'nl');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (19,N'Burkina Faso',N'BF',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (20,N'Bulgaria',N'BG',N'bg');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (21,N'Bahrain',N'BH',N'ar');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (22,N'Burundi',N'BI',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (23,N'Benin',N'BJ',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (24,N'Bermuda',N'BM',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (25,N'Brunei Darussalam',N'BN',N'ms');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (26,N'Bolivia',N'BO',N'es');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (27,N'Brazil',N'BR',N'pt');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (28,N'Bahamas',N'BS',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (29,N'Bhutan',N'BT',N'dz');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (30,N'Botswana',N'BW',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (31,N'Belarus',N'BY',N'be');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (32,N'Belize',N'BZ',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (33,N'Canada',N'CA',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (34,N'Cocos (Keeling) Islands',N'CC',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (35,N'Democratic Republic of the Congo',N'CD',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (36,N'Central African Republic',N'CF',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (37,N'Congo',N'CG',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (38,N'Switzerland',N'CH',N'de');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (39,N'Cote D''Ivoire (Ivory Coast)',N'CI',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (40,N'Cook Islands',N'CK',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (41,N'Chile',N'CL',N'es');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (42,N'Cameroon',N'CM',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (43,N'China',N'CN',N'zh');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (44,N'Colombia',N'CO',N'es');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (45,N'Costa Rica',N'CR',N'es');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (46,N'Cuba',N'CU',N'es');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (47,N'Cape Verde',N'CV',N'pt');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (48,N'Christmas Island',N'CX',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (49,N'Cyprus',N'CY',N'el');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (50,N'Czech Republic',N'CZ',N'cs');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (51,N'Germany',N'DE',N'de');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (52,N'Djibouti',N'DJ',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (53,N'Denmark',N'DK',N'da');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (54,N'Dominica',N'DM',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (55,N'Dominican Republic',N'DO',N'es');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (56,N'Algeria',N'DZ',N'ar');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (57,N'Ecuador',N'EC',N'es');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (58,N'Estonia',N'EE',N'et');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (59,N'Egypt',N'EG',N'ar');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (60,N'Western Sahara',N'EH',N'ar');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (61,N'Eritrea',N'ER',N'ti');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (62,N'Spain',N'ES',N'es');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (63,N'Ethiopia',N'ET',N'am');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (64,N'Finland',N'FI',N'fi');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (65,N'Fiji',N'FJ',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (66,N'Falkland Islands (Malvinas)',N'FK',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (67,N'Federated States of Micronesia',N'FM',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (68,N'Faroe Islands',N'FO',N'fo');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (69,N'France',N'FR',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (70,N'Gabon',N'GA',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (71,N'Great Britain (UK)',N'GB',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (72,N'Grenada',N'GD',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (73,N'Georgia',N'GE',N'ka');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (74,N'French Guiana',N'GF',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (75,N'Guernsey',N'GG',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (76,N'Ghana',N'GH',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (77,N'Gibraltar',N'GI',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (78,N'Greenland',N'GL',N'kl');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (79,N'Gambia',N'GM',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (80,N'Guinea',N'GN',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (81,N'Guadeloupe',N'GP',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (82,N'Equatorial Guinea',N'GQ',N'es');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (83,N'Greece',N'GR',N'el');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (84,N'S. Georgia and S. Sandwich Islands',N'GS',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (85,N'Guatemala',N'GT',N'es');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (86,N'Guinea-Bissau',N'GW',N'pt');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (87,N'Guyana',N'GY',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (88,N'Hong Kong',N'HK',N'zh');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (89,N'Honduras',N'HN',N'es');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (90,N'Croatia (Hrvatska)',N'HR',N'hr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (91,N'Haiti',N'HT',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (92,N'Hungary',N'HU',N'hu');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (93,N'Indonesia',N'ID',N'id');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (94,N'Ireland',N'IE',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (95,N'Israel',N'IL',N'he');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (96,N'India',N'IN',N'hi');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (97,N'Iraq',N'IQ',N'ar');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (98,N'Iran',N'IR',N'fa');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (99,N'Iceland',N'IS',N'is');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (100,N'Italy',N'IT',N'it');
 
INSERT INTO Countries (Id, Name, Code, Language) VALUES (101,N'Jamaica',N'JM',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (102,N'Jordan',N'JO',N'ar');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (103,N'Japan',N'JP',N'ja');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (104,N'Kenya',N'KE',N'sw');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (105,N'Kyrgyzstan',N'KG',N'ky');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (106,N'Cambodia',N'KH',N'km');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (107,N'Kiribati',N'KI',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (108,N'Comoros',N'KM',N'ar');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (109,N'Saint Kitts and Nevis',N'KN',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (110,N'Korea (North)',N'KP',N'ko');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (111,N'Korea (South)',N'KR',N'ko');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (112,N'Kuwait',N'KW',N'ar');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (113,N'Cayman Islands',N'KY',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (114,N'Kazakhstan',N'KZ',N'kk');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (115,N'Laos',N'LA',N'lo');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (116,N'Lebanon',N'LB',N'ar');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (117,N'Saint Lucia',N'LC',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (118,N'Liechtenstein',N'LI',N'de');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (119,N'Sri Lanka',N'LK',N'si');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (120,N'Liberia',N'LR',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (121,N'Lesotho',N'LS',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (122,N'Lithuania',N'LT',N'lt');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (123,N'Luxembourg',N'LU',N'lb');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (124,N'Latvia',N'LV',N'lv');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (125,N'Libya',N'LY',N'ar');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (126,N'Morocco',N'MA',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (127,N'Monaco',N'MC',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (128,N'Moldova',N'MD',N'ro');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (129,N'Madagascar',N'MG',N'mg');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (130,N'Marshall Islands',N'MH',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (131,N'Macedonia',N'MK',N'mk');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (132,N'Mali',N'ML',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (133,N'Myanmar',N'MM',N'my');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (134,N'Mongolia',N'MN',N'mn');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (135,N'Macao',N'MO',N'zh');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (136,N'Northern Mariana Islands',N'MP',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (137,N'Martinique',N'MQ',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (138,N'Mauritania',N'MR',N'ar');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (139,N'Montserrat',N'MS',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (140,N'Malta',N'MT',N'mt');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (141,N'Mauritius',N'MU',N'mfe');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (142,N'Maldives',N'MV',N'dv');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (143,N'Malawi',N'MW',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (144,N'Mexico',N'MX',N'es');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (145,N'Malaysia',N'MY',N'ms');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (146,N'Mozambique',N'MZ',N'pt');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (147,N'Namibia',N'NA',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (148,N'New Caledonia',N'NC',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (149,N'Niger',N'NE',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (150,N'Norfolk Island',N'NF',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (151,N'Nigeria',N'NG',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (152,N'Nicaragua',N'NI',N'es');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (153,N'Netherlands',N'NL',N'nl');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (154,N'Norway',N'NO',N'nb');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (155,N'Nepal',N'NP',N'ne');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (156,N'Nauru',N'NR',N'na');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (157,N'Niue',N'NU',N'niu');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (158,N'New Zealand (Aotearoa)',N'NZ',N'mi');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (159,N'Oman',N'OM',N'ar');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (160,N'Panama',N'PA',N'es');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (161,N'Peru',N'PE',N'es');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (162,N'French Polynesia',N'PF',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (163,N'Papua New Guinea',N'PG',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (164,N'Philippines',N'PH',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (165,N'Pakistan',N'PK',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (166,N'Poland',N'PL',N'pl');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (167,N'Saint Pierre and Miquelon',N'PM',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (168,N'Pitcairn',N'PN',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (169,N'Palestinian Territory',N'PS',N'ar');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (170,N'Portugal',N'PT',N'pt');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (171,N'Palau',N'PW',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (172,N'Paraguay',N'PY',N'es');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (173,N'Qatar',N'QA',N'ar');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (174,N'Reunion',N'RE',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (175,N'Romania',N'RO',N'ro');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (176,N'Russian Federation',N'RU',N'ru');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (177,N'Rwanda',N'RW',N'rw');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (178,N'Saudi Arabia',N'SA',N'ar');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (179,N'Solomon Islands',N'SB',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (180,N'Seychelles',N'SC',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (181,N'Sudan',N'SD',N'ar');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (182,N'Sweden',N'SE',N'sv');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (183,N'Singapore',N'SG',N'zh');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (184,N'Saint Helena',N'SH',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (185,N'Slovenia',N'SI',N'sl');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (186,N'Svalbard and Jan Mayen',N'SJ',N'no');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (187,N'Slovakia',N'SK',N'sk');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (188,N'Sierra Leone',N'SL',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (189,N'San Marino',N'SM',N'it');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (190,N'Senegal',N'SN',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (191,N'Somalia',N'SO',N'so');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (192,N'Suriname',N'SR',N'nl');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (193,N'Sao Tome and Principe',N'ST',N'pt');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (194,N'El Salvador',N'SV',N'es');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (195,N'Syria',N'SY',N'ar');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (196,N'Swaziland',N'SZ',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (197,N'Turks and Caicos Islands',N'TC',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (198,N'Chad',N'TD',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (199,N'French Southern Territories',N'TF',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (200,N'Togo',N'TG',N'fr');
 
INSERT INTO Countries (Id, Name, Code, Language) VALUES (201,N'Thailand',N'TH',N'th');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (202,N'Tajikistan',N'TJ',N'tg');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (203,N'Tokelau',N'TK',N'tkl');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (204,N'Turkmenistan',N'TM',N'tk');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (205,N'Tunisia',N'TN',N'ar');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (206,N'Tonga',N'TO',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (207,N'Turkey',N'TR',N'tr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (208,N'Trinidad and Tobago',N'TT',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (209,N'Tuvalu',N'TV',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (210,N'Taiwan',N'TW',N'zh');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (211,N'Tanzania',N'TZ',N'sw');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (212,N'Ukraine',N'UA',N'uk');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (213,N'Uganda',N'UG',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (214,N'Uruguay',N'UY',N'es');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (215,N'Uzbekistan',N'UZ',N'uz');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (216,N'Saint Vincent and the Grenadines',N'VC',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (217,N'Venezuela',N'VE',N'es');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (218,N'Virgin Islands (British)',N'VG',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (219,N'Virgin Islands (U.S.)',N'VI',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (220,N'Viet Nam',N'VN',N'vi');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (221,N'Vanuatu',N'VU',N'bi');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (222,N'Wallis and Futuna',N'WF',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (223,N'Samoa',N'WS',N'sm');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (224,N'Yemen',N'YE',N'ar');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (225,N'Mayotte',N'YT',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (226,N'South Africa',N'ZA',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (227,N'Zambia',N'ZM',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (228,N'Zaire (former)',N'ZR',N'fr');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (229,N'Zimbabwe',N'ZW',N'en');
INSERT INTO Countries (Id, Name, Code, Language) VALUES (230,N'United States of America',N'US',N'en');