INSERT INTO PricingPlanFeatures (Id, Name, PricingPlanId) VALUES (1, N'1 Listing', 1)
INSERT INTO PricingPlanFeatures (Id, Name, PricingPlanId) VALUES (2, N'30 Days Visibility', 1)
INSERT INTO PricingPlanFeatures (Id, Name, PricingPlanId) VALUES (3, N'Highlighted in Search Results', 1)
INSERT INTO PricingPlanFeatures (Id, Name, PricingPlanId) VALUES (4, N'5 Listings', 2)
INSERT INTO PricingPlanFeatures (Id, Name, PricingPlanId) VALUES (5, N'60 Days Visibility', 2)
INSERT INTO PricingPlanFeatures (Id, Name, PricingPlanId) VALUES (6, N'Highlighted in Search Results', 2)
INSERT INTO PricingPlanFeatures (Id, Name, PricingPlanId) VALUES (7, N'Unlimited Listings Listing', 3)
INSERT INTO PricingPlanFeatures (Id, Name, PricingPlanId) VALUES (8, N'90 Days Visibility', 3)
INSERT INTO PricingPlanFeatures (Id, Name, PricingPlanId) VALUES (9, N'Highlighted in Search Results', 3)
